# docker-compose up -d redis mongodb mysql postgres rabbitmq elasticsearch kibana
services:
  redis:
    container_name: redis_container
    image: redis:alpine
    restart: always
    ports:
      - "6380:6379"
    command: redis-server --loglevel warning
    volumes:
      - ./docker-volumes/cache:/data
  mongodb:
    container_name: mongo_container
    image: mongo:latest
    restart: always
    ports:
      - 27019:27018
    volumes:
      - ./docker-volumes/data:/data/db
  mysql:
    container_name: mysql_container
    image: mysql:8
    command: --mysql-native-password=ON
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=api
      - MYSQL_PASSWORD=api
      - MYSQL_USER=gigglobe
      - MYSQL_DATABASE=gigglobe_auth
    volumes:
      - ./docker-volumes/mysql:/var/lib/mysql:rw
    user: mysql
  postgres:
    container_name: postgres_container
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=api
      - POSTGRES_USER=gigglobe
      - POSTGRES_DATABASE=gigglobe_reviews
    volumes:
      - ./docker-volumes/postgres:/var/lib/postgresql
  rabbitmq:
    container_name: rabbitmq_container
    image: rabbitmq:3.13-rc-management-alpine
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=gigglobe
      - RABBITMQ_DEFAULT_PASS=api
    ports:
      # AMQP protocol port
      - "5672:5672"
      # Management UI - Dashboard
      - "15672:15672"
    networks:
      - elastic
  elasticsearch:
    container_name: elasticsearch_container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    restart: always
    environment:
      ES_JAVA_OPTS: -Xmx1g -Xms1g
      bootstrap.memory_lock: "true"
      discovery.type: single-node
      network.host: 0.0.0.0
      transport.host: 127.0.0.1
      http.host: 0.0.0.0
      xpack.security.enabled: "true"
      # Properties for Kibana dashboard
      xpack.security.authc.api_key.enabled: "true"
      xpack.monitoring.collection.enabled: "true"
      xpack.security.enrollment.enabled: "true"
      xpack.security.authc.token.enabled: "true"
      ELASTIC_PASSWORD: admin1234
    ports:
      - 9201:9200
      - 9300:9300
    volumes:
      - ./docker-volumes/elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - elastic
  kibana:
    container_name: kibana_container
    image: docker.elastic.co/kibana/kibana:8.11.0
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=["http://elasticsearch_container:9200"]
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=kibana
      - ELASTICSEARCH_SERVICEACCOUNT_TOKEN=AAEAAWVsYXN0aWMva2liYW5hL2dpZy1nbG9iZS1raWJhbmE6bzYxQkJlLWFRcW1Cd0xaMzQ1U1RJdw
      - XPACK_FLEET_AGENTS_ELASTICSEARCH_HOSTS=["http://elasticsearch_container:9200"]
    ports:
      - 5601:5601
    networks:
      - elastic
    volumes:
      - ./kibana.yaml:/usr/share/kibana/config/kibana.yml:ro
    depends_on:
      - elasticsearch
  notifications:
    container_name: notification_container
    build:
      context: server/notification-service
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 4001:4001
    env_file: server/notification-service/.env
    environment:
      - ENABLE_APM=0
      - NODE_ENV=development
      - CLIENT_URL=http://localhost:3005
      - RABBITMQ_ENDPOINT=amqp://gigglobe:api@rabbitmq_container:5672
      - SENDER_EMAIL=anderson.maggio21@ethereal.email
      - SENDER_EMAIL_PASSWORD=MRFV3UAnWUUrt8kh8c
      - ELASTIC_SEARCH_URL=http://elastic:admin1234@elasticsearch_container:9200
      - ELASTIC_APM_SERVER_URL=http://localhost:8200
      - ELASTIC_APM_SECRET_TOKEN=
    depends_on:
      - elasticsearch
      - rabbitmq
    networks:
      - elastic
  gateway:
    container_name: gateway_container
    build:
      context: server/api-gateway-service
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 4000:4000
    env_file: server/api-gateway-service/.env
    environment:
      - ENABLE_APM=0
      - GATEWAY_JWT_TOKEN=5c3e89094d1fbef6f61b6f62306b42e9
      - JWT_TOKEN=3fd25c6c069fdaa82be6034d835c17ac
      - NODE_ENV=development
      - SECRET_KEY_ONE=0598b1c7842470a18d4f3445af8d7271
      - SECRET_KEY_TWO=fe4636c767c0166a1a5e08b564d520a1
      - CLIENT_URL=http://localhost:3005
      - AUTH_BASE_URL=http://localhost:4002
      - USERS_BASE_URL=http://localhost:4003
      - GIG_BASE_URL=http://localhost:4004
      - MESSAGE_BASE_URL=http://localhost:4005
      - ORDER_BASE_URL=http://localhost:4006
      - REVIEW_BASE_URL=http://localhost:4007
      - REDIS_HOST=redis://redis_container:6379
      - ELASTIC_SEARCH_URL=http://elastic:admin1234@elasticsearch_container:9200
      - ELASTIC_APM_SERVER_URL=http://localhost:8200
      - ELASTIC_APM_SECRET_TOKEN=
    depends_on:
      - elasticsearch
    networks:
      - elastic

networks:
  elastic:
    name: elastic
