version: "1.9"
services:
  redis:
    container_name: redis_container
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --loglevel warning
    volumes:
      - ./docker-volumes/cache:/data
  mongodb:
    container_name: mongo_container
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./docker-volumes/data:/data/db
  mysql:
    container_name: mysql_container
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3603:3603"
    environment:
      - MYSQL_ROOT_PASSWORD=api
      - MYSQL_PASSWORD=api
      - MYSQL_USER=gigglobe
      - MYSQL_DATABASE=gigglobe_auth
    volumes:
      - ./docker-volumes/mysql:/var/lib/mysql
  postgres:
    container_name: postgres_container
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=api
      - POSTGRES_USER=gigglobe
      - POSTGRES_DATABASE=gigglobe_reviews
    volumes:
      - ./docker-volumes/postgres:/var/lib/postgresql
